version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "golang.org/x/*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "golang.org/x/time"
        versions: [">=0.15.0"]
