version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=integration
      - RABBITMQ_DEFAULT_PASS=integration
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s
