{{- range $value := .Values.beelzebubServiceConfigs }}
{{- $trimmed := trimSuffix ".yaml" $value.name }}
{{- $safeName := regexReplaceAll "[^a-z0-9-]" (lower $trimmed) "-" | trimAll "-" | trunc 63 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beelzebub-services-cm-{{ $safeName }}
data:
  {{ $value.name }}: |-
    {{- toYaml $value.config | nindent 4 }}
{{- end }}
