{{- range $value := .Values.beelzebubServiceConfigs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beelzebub-services-cm-{{ trimSuffix ".yaml" $value.name }}
  labels:
    {{- include "beelzebub-chart.labels" . | nindent 4 }}
data:
  {{ $value.name }}: |-
    {{- toYaml $value.config | nindent 4 }}
{{- end }}
