{{- range $value := .Values.beelzebubServiceConfigs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: beelzebub-services-cm-{{ trimSuffix ".yaml" $value.name }}
data:
  {{ $value.name }}: 
    {{- toYaml $value.config | nindent 4 }}
{{- end }}
