apiVersion: v1
kind: ConfigMap
metadata:
  name: "beelzebub-configmap"
  labels:
    {{- include "beelzebub-chart.labels" . | nindent 4 }}
data:
  beelzebub.yaml: |
    core:
    logging:
        debug: false
        debugReportCaller: false
        logDisableTimestamp: true
        logsPath: ./logs
    tracings:
        rabbit-mq:
        enabled: false
        uri: ""
    prometheus:
        path: "/metrics"
        port: ":2112"

 
