apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "beelzebub-chart.fullname" . }}
  labels:
    {{- include "beelzebub-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "beelzebub-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "beelzebub-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "beelzebub-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          volumeMounts:
            - name: config-core-volume
              mountPath: /configurations/beelzebub.yaml
              subPath: beelzebub.yaml
              readOnly: true
            {{- range $value := .Values.beelzebubServiceConfigs }}
            {{- $trimmed := trimSuffix ".yaml" $value.name }}
            {{- $safeName := regexReplaceAll "[^a-z0-9-]" (lower $trimmed) "-" | trimAll "-" | trunc 63 }}
            - name: config-services-volume-{{ $safeName }}
              mountPath: /configurations/services/{{ $value.name }}
              subPath: {{ $value.name }}
              readOnly: true
            {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $value := .Values.beelzebubServiceConfigs }}
            - name: {{ trimSuffix ".yaml" $value.name }}
              containerPort: {{ trimPrefix ":" $value.config.address | default $.Values.service.port }}
              protocol: TCP
            {{- end }}  
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-core-volume
          configMap:
            name: beelzebub-configuration
        {{- range $value := .Values.beelzebubServiceConfigs }}
        {{- $trimmed := trimSuffix ".yaml" $value.name }}
        {{- $safeName := regexReplaceAll "[^a-z0-9-]" (lower $trimmed) "-" | trimAll "-" | trunc 63 }}
        - name: config-services-volume-{{ $safeName }}
          configMap:
            name: beelzebub-services-cm-{{ $safeName }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
