apiVersion: v1
kind: Service
metadata:
  name: {{ include "beelzebub-chart.fullname" . }}
  labels:
    {{- include "beelzebub-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $value := .Values.beelzebubServiceConfigs }}
    - port: {{ .Values.service.port }}
      targetPort: {{ trimPrefix ":" $value.config.address }}
      protocol: TCP
      name: {{ trimSuffix ".yaml" $value.name }}
    {{- end }}  
  selector:
    {{- include "beelzebub-chart.selectorLabels" . | nindent 4 }}
