name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.0

    - name: Dependencies
      run: go mod download

    - name: Vet
      run: |
        go vet ./...

    - name: Build
      run: go build -v ./...

    - name: Unit tests
      run: |
        go test ./... -v -coverprofile coverage.tmp.out -covermode count
        go tool cover -func coverage.tmp.out

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Start integration test dependencies
      run: |
        make test.dependencies.start

    - name: Wait for RabbitMQ to be ready
      run: |
        sleep 2
        count=0
        until docker exec rabbitmq rabbitmqctl list_queues > /dev/null 2>&1; do
          count=$((count+1))
          if [ $count -gt 10 ]; then
            echo "RabbitMQ did not start within the specified time"
            exit 1
          fi
          echo "Waiting for RabbitMQ to start..."
          sleep 5
        done

    - name: Integration tests
      run: |
        make test.integration.verbose
        make test.dependencies.down
